export const MESSAGE = {
  CONGRATULATION: 'Your password has been reset.',
  REQUEST_SHOW_NAME: 'Unmask request granted.',
  REQUEST_REMASK: 'Profile re-masked successfully.',
  INCORRECT_LOGIN: 'Incorrect email address and  or password.',
  TITLE_CONFIRM_LOGOUT: 'Do you want to logout?',
  TITLE_CONFIRM_DELETE_JOB: 'Do you want to delete this job?',
  TITLE_CONFIRM_DELETE_REPORT: 'Do you want to delete?',
  TITLE_CONFIRM_MAKE_ACTIVE_JOB: 'Please complete your job posting before making it active?',
  TITLE_CONFIRM_MAKE_ACTIVE_JOB_CLOSED: 'Please complete your job posting before reposting it?',
  TITLE_CONFIRM_ADD_ASSESSMENT_JOB: 'Would you like to add selected assessment(s) to a New Job or an Existing Draft?',
  WARNING_ADD_JOBS: 'please select assessments to add job',
  WARNING_HOT_JOB_CARD: 'Please select featured date before job expiration day.',
  BTN_OK_TEXT: 'OK',
  BTN_DELETE_TEXT: 'Delete',
  BTN_SAVE_DRAFT_TEXT: 'Save draft',
  BTN_YES_TEXT: 'Yes',
  BTN_NO_TEXT: 'No',
  BTN_EDIT_TEXT: 'Edit',
  BTN_EDIT_ACTIVATE_TEXT: 'Complete',
  BTN_OK_DRAW: 'Withdraw',
  BTN_APPLY_TEXT: 'Apply',
  BTN_SAVE_TEXT: 'Save it as a draft',
  BTN_CANCEL_TEXT: 'Cancel',
  BTN_CONTINUE_TEXT: 'Continue',
  ACCESS_DENIED: 'Session Expired, Please relogin.',
  EXSITS_EMAIL: 'Email already exists. Please add a new email.',
  SUCCESSFULLY: 'Successfully.',
  DELETED_REPORTS: 'Successfully Deleted',
  SAVED_REPORTS: 'Successfully Saved',
  CONFIRM_DELETE: 'Are you sure you want to delete this item?',
  RESET_PASSWORD_SUCCESSFULY: 'Password has been updated successfully.',
  SENDMAIL_DELEGATE_SUCCESSFULY: 'Email has been sent successfully.',
  UPDATE_USER_INFORMATION_SUCCESSFULY: 'Your information has been saved successfully.',
  CREATE_ACCOUNT_JOBSEEKER_SUCCESSFULY: 'Account Successfully Created.',
  ADD_JOB_SUCCESSFULY: 'Job Added to Shopping Cart.',
  INVITED_MEMBER_SUCCESSFULY: 'Invited member successfully.',
  UPDATE_MEMBER_SUCCESSFULY: 'Update member successfully.',
  UPDATE_EMAIl_SUCCESSFULY: 'Update email successfully.',
  ADD_JOB_DRAFT_SUCCESSFULY: 'Job saved as draft successfully.',
  CONFIRM_PAYEMNT_SUCCESSFULY: 'Payment Successful.',
  UPDATE_JOB_SUCCESSFULY: 'Your job has been updated successfully.',
  UPDATE_FOLLOW_SUCCESSFULY: 'Employer has been followed successfully.',
  UPDATE_UNFOLLOW_SUCCESSFULY: 'Employer has been unfollowed successfully.',
  UPDATE_CARD_INFO_SUCCESSFULY: 'Your card info has been updated successfully.',
  CONFIRM_DUPPLICATE_JOB: 'Do you want to duplicate this job?',
  DUPLICATE_JOB_SUCCESSFULLY: 'Your job has been duplicated successfully.',
  DUPLICATE_ASSESSMENT_SUCCESSFULLY: 'Assessment Duplicated Successfully.',
  DELETE_JOB_SUCCESSFULLY: 'Your job has been deleted successfully.',
  DELETE_DELEGATE_ACCPOUNT_SUCCESSFULLY: 'This account has been removed successfully.',
  DELETE_JOB_CLOSE_SUCCESSFULLY: 'You have successfully withdrawn from this job.',
  DELETE_CUSTOM_ASSESSMENT_SUCCESSFULLY: 'Your custom assessment has been deleted successfully.',
  DELETE_CARD_SUCCESSFULLY: 'Your card has been deleted successfully.',
  DELETE_JOB_CARD_SUCCESSFULLY: 'Your job card has been deleted successfully.',
  UNAUTHORIZED: 'unauthorized',
  JOB_SEARCH_NOT_FOUND: 'No search results found',
  JOB_SEARCH_JOBSEEKER_NOT_FOUND: 'No job matching your criteria was found. Please try again with different search parameters and/or widen your filter settings.',
  NOTE_SELECT_AVATAR_JOB_SEEKER: 'Please select a photo with size of 800 x 800 pixels for better quality',
  NOTE_SELECT_AVATAR_EMPLOYER: 'Please select a photo with size of 1400 x 800 pixels for better quality',
  CONFIRM_DRAFT_JOB: 'All changes will not be saved. Are you sure you want to close it?',
  REPORT_COMPANY_SUCCESSFULY: 'Your report has been created successfully.',
  REPORT_JOB_SUCCESSFULY: 'Your report has been created successfully.',
  REPORT_USER_SUCCESSFULY: 'Your report has been created successfully.',
  SUM_POINT_TOO_MAX: 'Total weighting of assessment scores must equal 100%',
  POINT_EXIST_ZERO: 'The weighting value of 1 assessment must be greater than 0',
  CONFIRM_DRAW_JOB: 'Are you sure you want to withdraw your application?',
  CONFIRM_PAYMENT_ASSESSMENT: 'Your free test attempt has been run out. This test will charge you $... . Would you like to continue validating this skill?',
  APPLY_JOB_SUCCESSFULY: 'You have successfully applied for this job.',
  CREATE_CUSTOM_AEESEEMENT_SUCCESSFULY: 'Your custom assessment has been created successfully.',
  UPDATE_CUSTOM_AEESEEMENT_SUCCESSFULY: 'Your custom assessment has been updated successfully.',
  CONFIRM_APPLY_JOB: 'Are you sure you want to apply for this job?',
  CONFIRM_CLOSE: 'Are you sure you want to close?',
  CONFIRM_CLOSE_ACTIVE: 'Are you sure you want to discard changes?',
  CONFIRM_ICON_CLOSE: 'Are you sure you want to delete this posting?',
  BTN_CLOSE_TEXT: 'Close',
  ADD_NOTE_APPLICANTS: 'Your note has been added.',
  CONFIRM_SWITCH_IMOCHA: 'You will be redirected to the assessment. Would you like to continue?',
  CONFIRM_GO_TO_LOGIN: 'Continuing will log you out? Would you like to continue?',
  CONFIRM_GO_TO_LOGIN_REPORT: 'Continuing will log you out? Would you like to continue?',
  CONFIRM_RETRY_IMOCHA: 'You will be redirected to the assessment. Would you like to continue?',
  REMOVE_ASSESSMENT: 'The assessment has been removed successfully.',
  CONFIRM_REMASK_JOBSEEKER: 'Are you sure you want to remask your profile? This employer will no longer be able to see your profile picture and last name.',
  ADDED_ASSESSMENT: 'You have added the assessment successfully.',
  NO_RESULT_SEARCH_JOB: 'No results found. Please try again.',
  CONFIRM_DELETE_ACCOUNT: 'Are you sure you want to deactivate your account?',
  DELETE_ACCOUNT_SUCCESS: 'Your Account has been deactivated successfully.',
  SEND_FORM_HOMEPAGE_SUCCESS: 'Your form has been sent successfully.',
  INVITE_USER_SUCCESS: 'Member Added Successfully.',
  REMOVE_USER_SUCCESS: 'Member Removed Successfully.',
  CONFIRM_SHOW_AVATAR: 'Are you sure you want to show avatar?',
  REQUEST_UNMARK_SUCCESS: 'Your request has been sent successfully.',
  ERROR: 'Error',
  SET_UP_PASSWORD_SUCCESS: 'Your password has been set successfully.',
  INVITE_LIST_JOB_SUCCESS: 'This candidate has successfully received your job invitation.',
  TOTAL_POINT_CUSTOM_ASSESSMENT: 'Total point must be 100.',
  POINT_EXIST_ZERO_CUSTOM_ASSESSMENT: 'Point value of one question must be greater than 0.',
  CONFIRM_DELETE_EMPLOYER_PHOTO: 'Are your sure you want to remove this image?',
  ASSESSMENT_REQUIRED: 'All jobs must have at least one (1) assessment selected.',
  MAXIMUM_UPLOAD_FILE: 'Maximum Upload Size: 5 MB',
  WARNING_SIZE_UPLOAD_FILE: 'File size exceeds 5 MB limit.',
  WARNING_FILE_NOT_SUPPORT: 'This file type is not supported. Please select another one.',
  WARNING_SIZE_UPLOAD_IMAGE: 'Image size must be at least 15 KB.',
  WARNING_STATE_REQUIRED: 'Invalid State. Please enter the State with our suggestion below.',
  CONFIRM_UNFOLLOW_EMPLOYERES: 'Are you sure you want to unfollow?',
  CONFIRM_DELETE_DELEGATE_ACCOUNT: 'Are you sure you want to delete this user from your company?',
  CONFIRM_ASSESSMENT_TEST_NBR_AVAIL : 'You are out of remaining free attempts for this assessment. Continuing will use one (1) retake credit. Do you want to continue?',
  CONFIRM_ASSESSMENT_TEST_NBR_UNAVAIL: 'You are out of remaining free attempts for this assessment. Retaking this assessment will require one (1) retake credit. You can earn free retake credits by referring a friend or you can continue immediately and purchase a retake credit? Do you want to continue?',
  scoreApplyJobInProgress: 'Please wait while we calculate your test score. This could take up to one (1) minute.',
  UNSUBSCRIBE_SUUCCESS: 'Your feedback has been sent successfully.',
  SIGN_UP_SUCCESS: 'Signup Successful.',
  UPDATE_USER_SURVEY_SUCCESS: 'Your survey has been sent successfully.',
}
